# -*- coding: utf-8 -*-
"""internship1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vkx2X_SqckR-ZUo9_G55uFEEjMfSSOvD
"""

Name="kalai"
Age=18
CGPA=6.9
Placed=False
print("Student Name:",Name)
print("Age:",Age)
print("CGPA:",CGPA)
print("Placed:",Placed)
print(type(Name))
print(type(Age))
print(type(CGPA))
print(type(Placed))





